name: Run Postman Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v4

      # Step 2: Install Node + Newman + Reporter
      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Step 3: Run collection
      - name: Run Postman Collection
        run: |
          mkdir -p result
          newman run ./user.json \
            -g ./global.json \
            -e ./postman.json \
            --delay-request 1 \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export ./result/Report.html

      # Step 4: Upload report artifact
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: ./result/Report.html
          retention-days: 7  # mantém relatório por 7 dias
