name: Run Postman Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v4

      # Step 2: Instala Newman e Reporter
      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Step 3: Executa coleção e gera relatório com timestamp
      - name: Run Postman Collection
        run: |
          mkdir -p result
          timestamp=$(date +'%Y-%m-%d_%H-%M-%S')
          newman run ./user.json \
            -g ./global.json \
            -e ./postman.json \
            --delay-request 1 \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export ./result/Report-${timestamp}.html

      # Step 4: Publica relatórios no Pages
      - name: Upload report to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./result

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write      # necessário para publicar no Pages
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
